package ifer.web.shopping.db;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;// default package
// Generated Apr 29, 2017 8:55:17 PM by Hibernate Tools 4.3.1
import javax.validation.constraints.NotNull;

/**
 * User generated by hbm2java
 */
@Entity
public class User implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer userid;
	
	@NotNull
	private String name;
	
	@NotNull
	private String passwdhash;
	
	private String roles;
	
	@Version
	private int version;	

	public User() {
	}

	public User(String name, String passwdhash) {
		this.name = name;
		this.passwdhash = passwdhash;
	}

	public User(String name, String passwdhash, String roles) {
		this.name = name;
		this.passwdhash = passwdhash;
		this.roles = roles;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPasswdhash() {
		return this.passwdhash;
	}

	public void setPasswdhash(String passwdhash) {
		this.passwdhash = passwdhash;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}


	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

}
